ln -s ~/code/configs/karabiner ~/.config
ln -s ~/code/configs/zshrc ~/.zshrc
ln -s ~/code/configs/vimrc ~/.vimrc
ln -s ~/code/configs/ideavimrc ~/.ideavimrc
cp ~/.config/nvim/lua/user_example cp ~/.config/nvim/lua/user
ln -s $HOME/code/configs/nvim/lua/user/plugins/neo-tree.lua $HOME/.config/nvim/lua/user/plugins/neo-tree.lua
ln -s $HOME/code/configs/nvim/lua/user/init.lua $HOME/.config/nvim/lua/user/init.lua
ln -s $HOME/code/configs/config.fish $HOME/.config/fish/config.fish
ln -s "$HOME/code/configs/aerospace/aerospace.toml" "$HOME/.config/aerospace/aerospace.toml"
ln -sf ~/code/configs/claude/CLAUDE.md ~/.claude/CLAUDE.md
ln -sf ~/code/configs/claude/commands ~/.claude/commands
